networks:
  chamba_network:
    driver: bridge

services:
  chamba_users_jobs_db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: chamba_users_jobs_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: 'UTC-4'
    command: -p 4040
    ports:
      - 4040:4040
    volumes:
      - chamba-users-jobs-data:/var/lib/postgresql/data
    networks:
      - chamba_network

  chamba_seq:
    image: datalust/seq:2024
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - chamba_network

  consul:
    image: hashicorp/consul:1.20
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    ports:
      - '8500:8500'
    volumes:
      - consul-data:/consul/data
    networks:
      - chamba_network

volumes:
  chamba-users-jobs-data:
  chamba-db-admin-data:
  consul-data: