networks:
  chamba_network:
    driver: bridge

services:
  chamba_db:
    image: postgres:16.0
    container_name: chamba_db
    restart: always
    environment:
      POSTGRES_DB: chamba_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: 'UTC-4'
    command: -p 4040
    ports:
      - 4040:4040
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h chamba_db -p 4040 -d chamba_db']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chamba_network

  chamba_db_admin:
    image: dpage/pgadmin4:7.8
    container_name: chamba_db_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      chamba_db:
        condition: service_healthy
    networks:
      - chamba_network

  seq:
    image: datalust/seq:2024
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - chamba_network

volumes:
  pgadmin-data:
  postgres-data:
