apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seq
  name: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:2024
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: seq-service
  name: seq-service
spec:
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
