apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-jobs
  name: users-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-jobs
  template:
    metadata:
      labels:
        app: users-jobs
    spec:
      containers:
      - name: users-jobs
        image: usersjobsapi.azurecr.io/usersjobsapi:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: users-jobs-service-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: users-jobs-service
  name: users-jobs-service
spec:
  selector:
    app: users-jobs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer