networks:
  nirvana-premium_chamba_network:
    external: true

services:
  api.gateway:
    image: api.gateway:latest
    container_name: api.gateway
    restart: on-failure
    hostname: api.gateway
    build:
      context: ../..
      dockerfile: core/api-gateway/src/Api.Gateway/Dockerfile
    ports:
      - 9500:8080
    networks:
      - nirvana-premium_chamba_network
