networks:
  nirvana-premium_chamba_network:
    external: true

services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ../../.env:/app/.env
      - ../../firebase.json:/app/firebase.json
    networks:
      - nirvana-premium_chamba_network
